image: docker:stable-git

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  BASEIMAGE: registry.gitlab.com/koha-community/docker/koha-docker
  CACHE_VERSION: latest
  KOHA_VERSION: "23.05"

before_script:
  - docker login -u $PAUSER -p $PATOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker pull $BASEIMAGE:$CACHE_VERSION || true
    - docker build --build-arg KOHA_VERSION=$KOHA_VERSION --cache-from $BASEIMAGE:$CACHE_VERSION -t $BASEIMAGE:$CI_COMMIT_TAG .
    - docker tag $BASEIMAGE:$CI_COMMIT_TAG $BASEIMAGE:$CACHE_VERSION
    - docker push $BASEIMAGE:$CI_COMMIT_TAG
    - docker push $BASEIMAGE:$CACHE_VERSION
  only:
    - tags
